### ISSUE TITLE
Remove duplicate code to check email/username in volunteer_controller

### ISSUE THREAD

**Issue by rachelc421** [kiva/CrowdVet#12]
The following code in volunteer_controller checks if there is a duplicate entry in the Volunteer table. This logic is already performed 
exports.createVolunteer = function(req, res) {
    var email = req.body.email_address;
    var usern = req.body.username;

```
Volunteer.findOne( {$or: [{'email_address': email}, {'username': usern}]},
    function(err, volunteer) {
        if(volunteer != null) {
            //this is a duplicate entry
            req.session.email_duplicate = true;
            res.redirect('/volunteer/sign-up');
        } else {
            var volunteer = new Volunteer({
                first_name: req.body.first_name,
                last_name: req.body.last_name,
                email_address: req.body.email_address,
                username: req.body.username,
                password: SHA3(req.body.password).toString(),
                //TODO: Add confirm password?
                finished_training: false,
                approved: false,
                linked_in: req.body.linked_in,
                volunteer_question: req.body.volunteer_question
            });
            volunteer.save(function(err, volunteer) {
                if(err) {console.log(err);}
                else {
                    req.session.admin = volunteer.is_admin;
                    req.session.logged = true;
                    req.session.volunteerId = ObjectId(volunteer._id.toString());
                    req.session.email = volunteer.email_address;
                    req.session.fullname = volunteer.first_name + " " + volunteer.last_name;
                    req.session.finished_training = volunteer.finished_training;
                    res.redirect('/volunteer/training');
                }
            });
        }
    });
```

};

The above code has duplicate logic as the code block below in the volunteer controller. 
exports.check_email_username = function(req, res) {
    var email = req.body.email;
    var username = req.body.username;
    Volunteer.findOne({'email_address': email}, function(err, volunteer_email) {
        var email_exists = (volunteer_email != null);
        Volunteer.findOne({'username': username}, function(err, volunteer_username) {
            var username_exists = (volunteer_username != null);
            if (email_exists && username_exists) {
                res.send("both");
            } else if (email_exists) {
                res.send("email");
            } else if (username_exists) {
                res.send("username");
            } else {
                res.send("neither");
            }
        });
    });
}

**Comment by abhishekbh** [comment]
Actually in a very convoluted way, this logic seems to enforce the "Incorrect Login" message. For that sake it might be worth it leaving it behind at the moment. Closing :(.
