### ISSUE TITLE
Fix typo in the volunteer agreement check on the Volunteer Sign-Up Form

### ISSUE THREAD

**Issue by rachelc421** [kiva/CrowdVet#16]
Current text: 
Please take a moment to read and sign this agreement. It is a two step process.volunteer agreement.
*volunteer agreement is linked to: https://na2.docusign.net/member/PowerFormSigning.aspx?PowerFormId=dfc19b21-39ee-40ac-98c0-ecda07cbc268

New text: 
Please read and sign this two-step volunteer agreement. 
*volunteer agreement should still be linked to the URL above.

**Comment by rachelc421** [comment]
@danielanastos what are your thoughts on updating the text to be: "I have read and signed this two-step volunteer agreement." ? 

Shortening the length of the sentence will fit better on the form. Since it's a checkbox for an action the user needs to take, it also makes sense to have it in the point of view of the user. But let me know your thoughts!

**Comment by danielanastos** [comment]
I like it. Is the volunteer agreement a hyperlink on the words 'volunteer agreement'? Or is there a link below?

**Comment by rachelc421** [comment]
@danielanastos Yep it's a hyperlink on the words "volunteer agreement." Looks like:

![image](https://cloud.githubusercontent.com/assets/13949658/18104308/6c2683e8-6eaf-11e6-8b81-fd3b59fa27c2.png)

**Comment by danielanastos** [comment]
Super clear. Push that whenever you're feeling it.

**Comment by abhishekbh** [comment]
You guys are awesome, I love the discussions and the activity on here; keep kicking it!

**Comment by rachelc421** [comment]
Done!!
