### ISSUE TITLE
Review Page Multiple Links

### ISSUE THREAD

**Issue by danielanastos** [kiva/CrowdVet#17]
On the review page, multiple links show up. What would be great is if we had only one link show up which was the folder with all the other links inside of it. It is structured to be one folder in google drive, but for some reason, the "gdocs-file-list" command pulls everything in the google drive folder and shows it on the page.
Can we fix this?
@abhishekbh

**Comment by abhishekbh** [comment]
What if we do both?
Leave the tree view, but also have a single clickable link on the top with access to the full folder?

**Comment by abhishekbh** [comment]
@danielanastos, check out solution here: https://github.com/kiva/CrowdVet/commit/accb348befa7b7458486bedcbc333755647700b5

Feel free to close after

**Comment by danielanastos** [comment]
@abhishekbh this is awesome. I love it
