### ISSUE TITLE
Volunteer Sign Up Page - Volunteer Agreement Change

### ISSUE THREAD

**Issue by danielanastos** [kiva/CrowdVet#20]
**I would like to change line 62 in volunteer_signup.ejs to say "Please click this volunteer agreement link and sign the docusign. This is required for participation in the program."**
The words "volunteer agreement" should still be the ones with the ahref. 

We have had 3/7 of our first users not sign the volunteer agreement. I do not know if they are simply checking the box or not going through both of the steps, but something is unclear. 

@abhishekbh

**Comment by abhishekbh** [comment]
done

**Comment by danielanastos** [comment]
Thank you. You're a hero.
