### ISSUE TITLE
Sign up Page - Changing Volunteer Agreement

### ISSUE THREAD

**Issue by danielanastos** [kiva/CrowdVet#21]
Make it mandatory to sign docusign, and then checkbox or submit button will come up.

**Comment by MaxHasan** [comment]
embedded iframe programmed in test environment; need to push live

**Comment by abhishekbh** [comment]
Seems like this is done, though the iframe should probably be resized.
Close this?

**Comment by danielanastos** [comment]
Abhishek is back!!!!!!!!! Yo how was Colombia? Idk if you can throw pics in the comment section, but if you can, please do.

**Comment by danielanastos** [comment]
Ya we should close it.
