### ISSUE TITLE
Review Page

### ISSUE THREAD

**Issue by danielanastos** [kiva/CrowdVet#23]
Google API url link is not showing up on review page. Really need this back.

**Comment by MaxHasan** [comment]
Line 23 on review page: <div id="gdocs-file-list"></div>
not pulling necessary Google folder

**Comment by ebalcomb** [comment]
so it used to work?

**Comment by danielanastos** [comment]
It was working for sure on Saturday. And the google API still works on other parts of the website, like after you complete a review. Its just when you are doing the review, the URL link does not appear, which is really the only time it needs to work.
