### ISSUE TITLE
Add 3 more questions to Volunteer Sign Up Page

### ISSUE THREAD

**Issue by danielanastos** [kiva/CrowdVet#3]
@abhishekbh 
The idea here is to garner data on the volunteers. This will give us a good idea of who these people are what the interested in. This will help us give them loan products they want to review, adding user value and making it personalized. Additionally, this future data might allow us to better target future potential volunteers.

It would ideal if these questions were set up as check boxes so users can check more than one answer. And it would be nice if there was an other option so they could write in an answer that wasn't there.

Change 1
In what languages would you feel comfortable reading the due diligence documents?

English
Spanish
French
Portuguese
Russian
Mandarin
Other: Please Input

Change 2
In what regions are you most interested?

Global
North America
Latin America
Caribbean
Africa
Middle East
Central Asia
South Asia
East Asia
South Asia
Other: Please Input

Change 3
In what sectors are you most interested?

Agricultural Products and Services
Aquaculture and Fisheries
Clean Energy and Power
Community Development
Distribution and Retail
Education
Food and Beverages
Livestock and Poultry
Financial Services
Health
Services and Supplies
Hotels and Tourism
ICT
Manufacturing
Natural Resources and Conservation
Water and Sanitation
Other: Please Input

Code for clickable check box questions:
http://stackoverflow.com/questions/6293588/how-to-create-an-html-checkbox-with-a-clickable-label
http://jsfiddle.net/qYZFJ/

**Comment by abhishekbh** [comment]
So what's the call on this, are we still doing this?
@avgj0e @danielanastos

**Comment by danielanastos** [comment]
Because Carlos wants push this thing out to the first five people combined with the fact that it is difficult to sync user's information to the admin page, we decided to wait for this iteration but continue to work on it. Thanks to Rachel. Because I have no idea how to do it.

**Comment by avgj0e** [comment]
Done. https://github.com/kiva/CrowdVet/tree/Issue-3-Fix-Added-more-questions
